### ISSUE TITLE
Wobbles in sound field of localwfs for some plane wave directions

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs#28]
![localsfs_wobbles](https://cloud.githubusercontent.com/assets/173624/5700557/6024583a-9a40-11e4-97e6-863d71517b1b.png)

As you can see in the above image the sound of the plane wave has some strange wobbles if the plane wave goes to the direction [1 -1 0] instead of [0 -1 0]. Have you an idea if this is correct?

By the way I renamed test_virtualsecondarysources.m to test_localwfs.m and added more array setups.

**Comment by fietew** [comment]
Have you checked the resolution of the soundfield evaluation? Maybe its just a matter of aliasing introduced by the finite resolution of the images?

**Comment by hagenw** [comment]
You are correct, I changed the resolution to 1000 (b6c29f178b5f8b451133ce023c14d2aa5df21cb0) and now it looks as desired.
