### ISSUE TITLE
NFC-HOA orders for time-domain driving functions

### ISSUE THREAD

**Issue by narahahn** [sfstoolbox/sfs#56]
Unlike for monochromatic cases, it seems that the Ambisonic order cannot be freely chosen for time-domain NFC-HOA driving function. It only works if the order is an integer multiple of the number of secondary sources, of vice versa. I started to implement for arbitrary integer orders. Would it be worth doing this?

**Comment by hagenw** [comment]
That is another good point. It would be a very good idea as we would have a big problem otherwise.
A few comments:
1. I have fixed a small error, see e170daa9a2f3df8fdbcf218fdf151ffb0a08a3f5 and 78e2b5dad2e6ebcb2e3d9c22229adc86e728b285
2. As we have corrected the behavior of `nfchoa_order()` -- see 422b4f9ede7e4527f1d6591cccca8514e204c351 -- it will not return not a multiple of the secondary sources for band-limited NFC-HOA. For example:
```Matlab
>> conf = SFS_config;
>> sound_field_imp_nfchoa([-2 2],[-2 2],0,[0 -1 0],'pw',300,conf)
Error using driving_function_imp_nfchoa (line 157)
DRIVING_FUNCTION_IMP_NFCHOA: the given number of secondary sources (64) cannot be subsampled to 62 driving signals. Choose a NFC-HOA order that is a multiple of 30.

Error in sound_field_imp_nfchoa (line 94)
d = driving_function_imp_nfchoa(x0,xs,src,conf);
```
As you can see the numbers in the error message are now also broken, but the more important thing is that for band-limited NFC-HOA we cannot met the desired multiple condition. We have 64 secondary sources, which corresponds to an order of 31 (instead of 32 as it was before we corrected `nfchoa_order()`) which will not work with 64 secondary sources.

If you have an idea how to fix this, it would be great if you could push a new branch and create a pull request for this.

**Comment by narahahn** [comment]
I created a branch `nfchoa_arbitraryorder`. Now, the time-domain driving functions can be computed for any orders.

```matlab
conf = SFS_config;
conf.secondary_sources.number = 64;
conf.driving_functions = 'default';
conf.plot.usenormalisation = false;
conf.plot.usedb = false;

x0 = secondary_source_positions(conf);
X = [-2 2];
Y = [-2 2];
Z = 0;
xs = [0,-1,0];
src = 'pw';
t = 200;
pulse = transpose(hann_window(5,5,10));

conf.nfchoa.order = [];
d = driving_function_imp_nfchoa(x0,xs,src,conf);
d = convolution(d,pulse);
sound_field_imp(X,Y,Z,x0,'ps',d,t,conf);
caxis([-1 1]/4)
```
![nfchoa_imp_n031](https://cloud.githubusercontent.com/assets/8125968/13054835/07be108a-d40c-11e5-95c9-4512dd816537.png)


```matlab
conf.nfchoa.order = 8;
d = driving_function_imp_nfchoa(x0,xs,src,conf);
d = convolution(d,pulse);
sound_field_imp(X,Y,Z,x0,'ps',d,t,conf);
caxis([-1 1]/4)
```
![nfchoa_imp_n008](https://cloud.githubusercontent.com/assets/8125968/13054841/0faedf22-d40c-11e5-9103-90e72589983b.png)


```matlab
conf.nfchoa.order = 200;
d = driving_function_imp_nfchoa(x0,xs,src,conf);
d = convolution(d,pulse);
sound_field_imp(X,Y,Z,x0,'ps',d,t,conf);
caxis([-1 1]/4)
```
![nfchoa_imp_n200](https://cloud.githubusercontent.com/assets/8125968/13054846/1310d54e-d40c-11e5-8e46-cf9565149aca.png)

In the above examples, the bilinear transform was used to convert the poles and zeros in the Laplace domain to the z-domain. When the matched z-transform is used for orders greater than 84, there are some noise-like components in the synthesized field.
```matlab
conf.driving_functions = 'matchedz';
conf.nfchoa.order = 85;
d = driving_function_imp_nfchoa(x0,xs,src,conf);
d = convolution(d,pulse);
sound_field_imp(X,Y,Z,x0,'ps',d,t,conf);
caxis([-1 1]/4)
```
![nfchoa_imp_n085](https://cloud.githubusercontent.com/assets/8125968/13054980/e8e25800-d40c-11e5-9e1e-74364d3ac534.png)

**Comment by hagenw** [comment]
Interesting, it looks a little bit similar to https://github.com/hagenw/phd-thesis/tree/master/03_sound_field_errors_and_their_perceptual_relevance/fig3_13
I will test it further, also #57, but it could happen that I will need a few days.

**Comment by narahahn** [comment]
You are right. The maximum order in you simulation (256) is also much greater than the anti-alliasing order (31), the results are supposed to be similar to mine (order of 200). In fact, the result is nearly identical even if the order is increased up to 500.

![nfchoa_imp_n200](https://cloud.githubusercontent.com/assets/8125968/13144089/a4c2d63e-d648-11e5-9050-4c5c4a217468.png)
![nfchoa_imp_n500](https://cloud.githubusercontent.com/assets/8125968/13144092/a851a410-d648-11e5-8cd2-79d330b5a477.png)

At this point, I am not sure if the simulation results are correct for very high orders (above 85). As mentioned in [#57](https://github.com/sfstoolbox/sfs/issues/57), there are some suspicious behavior in the driving functions. I think we first have to check the zeros of the spherical Hankel functions.

**Comment by hagenw** [comment]
I included your changes regarding the arbitrary orders into `master` and deleted the `nfchoa_arbitraryorder` branch. What is not included is the part coming from the `nfchoa_sosfilter` branch, due to the problems discussed here: https://github.com/sfstoolbox/sfs/pull/65

**Comment by hagenw** [comment]
I have looked again at the NFC-HOA simulations and the new behavior of using arbritrary orders. The interpolation we are doing now introduces some artifacts and I was wondering if this is natural and cannot be avoided or if we could change something.

Here is the result as it was before with version 2.0.0 (it uses 64 loudspeakers and uses order 32, which can be done without interpolation, by just using every second loudspeaker):
```Bash
$ git checkout 2.0.0
```
```Matlab
conf = SFS_config_example;
conf.plot.usedb = 1;
sound_field_imp_nfchoa([-2 2],[-2 2],0,[0 2 0],'ps',200,conf);
```
![nfchoa_old](https://cloud.githubusercontent.com/assets/173624/13631524/6f3f4a72-e5e5-11e5-8fb3-c331937b15e8.png)

And here is the result as it implemented now, which has the advantage to use arbritry orders ( it uses 64 loudspeakers and an order of 31):
```Bash
$ git checkout master
```
```Matlab
conf = SFS_config;
conf.plot.usedb = 1;
sound_field_imp_nfchoa([-2 2],[-2 2],0,[0 2 0],'ps',200,conf);
```
![nfchoa_new](https://cloud.githubusercontent.com/assets/173624/13631562/aaeef752-e5e5-11e5-82f1-dd14e10ae4a6.png)

**Comment by narahahn** [comment]
I think the difference comes from the relation of the number of secondary sources (`nls`) and the NFC-HOA order (`order`).

In the earlier version of `driving_function_imp_nfchoa.m` (before this branch), the driving function is computed for `-order:order` and the `-order`-th row (i.e. the first row of the matrix `d`) is discarded if the number of loudspeaker is even. The resulting matrix has the size of `2*order-by-N`. The driving functions are then computed by spatial inverse Fourier transform. But this works only if `order=nls/2` which is not the correct maximum order. In version 2.0.0, the function `nfchoa_order.m` was still incorrect and you fixed it in 422b4f9ede7e4527f1d6591cccca8514e204c351. In the current `driving_function_imp_nfchoa.m`, the NFC-HOA order is `order=nls/2-1` for even `nls` if the order is not specified.

Still, the simulation result of the current version looks a bit strange, because of the small wavelets. But you get a similar result in version 2.0.0 if you slightly move the virtual source.


`$ git checkout 2.0.0`
```matlab
sound_field_imp_nfchoa([-2 2],[-2 2],0,[0.1 2 0],'ps',200,conf);
```
![nfchoa_ver2](https://cloud.githubusercontent.com/assets/8125968/13639431/0052c072-e611-11e5-92c8-fdb8bf7fd15a.png)

**Comment by hagenw** [comment]
That is interesting, I never shifted the point source away from `x=0` before, I guess. By the way for plane waves this does not happen in version 2.0.0.

To conclude: the new behavior is normal and not a bug as it is inherent to the implementation?

**Comment by narahahn** [comment]
I think it is normal.

By the way, in certain cases, we also get "clean" results with the current version.

```matlab
conf.secondary_sources.number = 63;
conf.nfchoa.order = 31;
sound_field_imp_nfchoa([-2 2],[-2 2],0,[2,0,0],'ps',200,conf);
```
![nfchoa_clean](https://cloud.githubusercontent.com/assets/8125968/13640209/09d63900-e614-11e5-8574-6d0e88fceb49.png)

```matlab
conf.secondary_sources.number = 63;
conf.nfchoa.order = 31;
sound_field_imp_nfchoa([-2 2],[-2 2],0,[-1,0,0],'pw',200,conf);
```
![nfchoa_pw_clean](https://cloud.githubusercontent.com/assets/8125968/13640272/3ea59ad6-e614-11e5-99e5-2cd3c4a14164.png)
