### ISSUE TITLE
Enable two-channel headphone compensation

### ISSUE THREAD

**Issue by VeraE** [sfstoolbox/sfs#85]
I suggest to enable two-channel headphone compensation. I think this could be done easily by allowing `convolution()` to accept two matrices as input that have one dimension of equal length.
I could do this myself if there are no problems likely to arise from this change?

**Comment by hagenw** [comment]
I guess it should indeed not a big problem to upgrade `convolution()` to deal with two matrices. Would be great if you could test this.

For the general topic of headphone compensation:
The headphone compensation from Alex Lindau (I guess 8 years ago) was two-channel based, but at one point we had a discussion that it seemed a little bit strange to us to have two different filters as you normally never have the exact same headphone, but only the same model.
I guess in your case you would like to use the exact headphone and you have some significant differences between left and right channel?

**Comment by VeraE** [comment]
Yes, I can use the exact headphone that the HpTF measurements for the compensation filters have been performed with. I wouldn't call the differences significant, though... Regardless of what I will be using in a listening test, I thought this would be a sensible feature.
Should I just create a new branch for this?

**Comment by hagenw** [comment]
Yes, a new branch with a name like hptf_convolution or something like this would be nice.

The other function which is involved is `compensate_headphone()`I guess, there we should then make sure that it will work with one channel as well as two channel HpTFs.
